apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
        - name: html
          image: loveisall/html:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 8081
      nodePort: 30003
  selector:
      app: html
